title: SenZhang's Homepage
page-top-title: Sen Zhang
top-section-bg-text: Be what I wanna be.
home-subtitle: Sen Zhang&ensp;|&ensp;张森
copyright-text: '&copy; Sen Zhang 2025. All Rights Reserved.'
email: "zhangsen1005@outlook.com"